### PR TITLE
Adding a Nextra site to apps/docs and adding the readme as different …

### PR DESCRIPTION
**Pull request by xaviemirmon**
…pages and sections

### CODE REVIEW

**Comment by xaviemirmon** [comment]
@chrisvxd for #24 This is very much a WIP progress but I've split out the readme in to a Nextra docs site.

**Comment by xaviemirmon** [comment]
This has been set up using the yarn monorepo so to run, you just need to use the following command.

```sh
yarn workspace docs dev
```

**Review by chrisvxd — CHANGES_REQUESTED** [review]
Awesome, thanks for setting this up and cribbing out a basic structure!

Can you run prettier on this? The build will fail until that passes.

I think we should merge this in to give us an anchor to contribute docs into. I'll wait to setup CI until we've got a baseline we're happy with.

**Comment by xaviemirmon** [comment]
Done! I had to add the mdx extension to the package.json command but it should pass now. 🤞

**Review by chrisvxd — APPROVED** [review]

**Comment by chrisvxd** [comment]
@xaviemirmon awesome, have approved. Conflicts need resolving before I can merge.

**Pull request merged**
