### PR TITLE
feat: adding hidden field to BaseField

### PR DESCRIPTION
**Pull request by xxxijustwei**
- Added `hidden` property to BaseField type in packages/core/types/Fields.ts
- Modified AutoField component to handle hidden fields in packages/core/components/AutoField/index.tsx
- Updated other Field type definitions in packages/core/types/Fields.ts

Usage Examples:
```tsx
export type TestProps = {
    language: "en" | "fr" | "es";
    title: {
        en: string;
        fr: string;
        es: string;
    }
}

export const Test: ComponentConfig<TestProps> = {
    resolveFields: (data) => ({
        language: {
            type: "radio",
            options: [
                { label: "English", value: "en" },
                { label: "French", value: "fr" },
                { label: "Spanish", value: "es" },
            ],
        },
        title: {
            type: "object",
            objectFields: {
                en: {
                    type: "text",
                    hidden: data.props.language !== "en",
                },
                fr: {
                    type: "text",
                    hidden: data.props.language !== "fr",
                },
                es: {
                    type: "text",
                    hidden: data.props.language !== "es",
                },
            }
        }
    }),
    render: ({ language, title, puck: { isEditing } }) => {
        const i18nLang = useCurrentLocale();
        return <div>{title[isEditing ? language : i18nLang]}</div>
    },
}
```

### CODE REVIEW

**Review by chrisvxd — COMMENTED** [review]
Hey @xxxijustwei! Thanks for the contribution.

I'm a little unsure whether we want to add this, since it's already technically already possible by using optional props and only adding the fields you want to show.

Granted, it's not quite as convenient as a `hidden` (or `visible`) parameter, but it works. 

Have you considered this?

```tsx
export type TestProps = {
  language: "en" | "fr" | "es";
  title: {
    en?: string;
    fr?: string;
    es?: string;
  };
};

export const Test: ComponentConfig<TestProps> = {
  resolveFields: (data) => {
    const title: ObjectField<TestProps["title"]> = {
      type: "object",
      objectFields: {},
    };

    if (data.props.language === "en") {
      title.objectFields.en = {
        type: "text",
      };
    } else if (data.props.language === "fr") {
      title.objectFields.fr = {
        type: "text",
      };
    } else if (data.props.language === "es") {
      title.objectFields.es = {
        type: "text",
      };
    }

    return {
      language: {
        type: "radio",
        options: [
          { label: "English", value: "en" },
          { label: "French", value: "fr" },
          { label: "Spanish", value: "es" },
        ],
      },
      title,
    };
  },
  render: ({ language, title, puck: { isEditing } }) => {
    const i18nLang = useCurrentLocale();
    return <div>{title[isEditing ? language : i18nLang]}</div>;
  },
};
```

**Comment by xxxijustwei** [comment]
> 嘿@xxxijustwei！感谢您的贡献。
> 
> 我有点不确定我们是否要添加这个，因为从技术上讲，通过使用可选道具并仅添加您想要显示的字段已经是可能的。
> 
> 当然，它不如`hidden`(或`visible`) 参数那么方便，但它确实有效。
> 
> 你考虑过这个吗？
> 
> ```tsx
> export type TestProps = {
>   language: "en" | "fr" | "es";
>   title: {
>     en?: string;
>     fr?: string;
>     es?: string;
>   };
> };
> 
> export const Test: ComponentConfig<TestProps> = {
>   resolveFields: (data) => {
>     const title: ObjectField<TestProps["title"]> = {
>       type: "object",
>       objectFields: {},
>     };
> 
>     if (data.props.language === "en") {
>       title.objectFields.en = {
>         type: "text",
>       };
>     } else if (data.props.language === "fr") {
>       title.objectFields.fr = {
>         type: "text",
>       };
>     } else if (data.props.language === "es") {
>       title.objectFields.es = {
>         type: "text",
>       };
>     }
> 
>     return {
>       language: {
>         type: "radio",
>         options: [
>           { label: "English", value: "en" },
>           { label: "French", value: "fr" },
>           { label: "Spanish", value: "es" },
>         ],
>       },
>       title,
>     };
>   },
>   render: ({ language, title, puck: { isEditing } }) => {
>     const i18nLang = useCurrentLocale();
>     return <div>{title[isEditing ? language : i18nLang]}</div>;
>   },
> };
> ```
Okay, i will consider this.
Thanks!

**Comment by Benjamin-Yu-Sheng-Chang** [comment]
Hi, I understand the solution, but in my case, the required field is id, which is already defined in defaultProps. I’d like to avoid exposing the id to the user. Is there a workaround for this scenario?

**Comment by FedericoBonel** [comment]
Hey @Benjamin-Yu-Sheng-Chang,  

You can simply not render a field for that specific `id` prop.  If you're using TypeScript, you'll also want to mark it as optional in your types so TypeScript doesn’t throw an error. Something like this:

```tsx
import { type Config } from "@measured/puck";

type Props = {
  Example: { myId?: string; someVisibleProp: string };
};

export const config: Config<Props> = {
  components: {

    Example: {
      fields: {
        someVisibleProp: { type: "text" },
      },
      defaultProps: {
        someVisibleProp: "Default Value",
      },
      render: ({ myId, someVisibleProp }) => {
        const myCastedId = myId ?? ""; // Cast it to string

        return <div>{someVisibleProp}</div>;
      },
    },
  },
};

export default config;
```

If you wanted, you could also mark the field as [read-only](https://puckeditor.com/docs/api-reference/configuration/component-config#datareadonly-1). That way, the user would be able to see the value, but not modify it.

**Pull request closed without merging**
