### PR TITLE
Fix: `position: fixed;` elements escape editor

### PR DESCRIPTION
**Pull request by JakeSidSmith**
Added transform to root element so `position: fixed;` elements sit relative to it.

Pictured below is the `apps/demo` with the following added to the `config/root.tsx`.

```tsx
    <header
        style={{
          position: "fixed",
          top: 0,
          left: 0,
          width: "100%",
          backgroundColor: "white",
          zIndex: 1000,
        }}
      >
```

It doesn't behave like a `position: fixed;` element normally would due to the scrolling being on an element outside of the one with the transform, but it does allow you to access the editor navigation while you have a fixed navbar.

Screenshot 2023-10-07 at 22 53 13

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
> Can't believe I got this far in my career without knowing this trick.

I only found out about it because of the bugs it caused. 😂

**Comment by chrisvxd** [comment]
@JakeSidSmith Unfortunately I've had to roll this back in our demo deployment as it's causing the drag positioning to break, which relies on position fixed. I missed this during review. You should be able to recreate locally if you're interested.

I haven't got a patch yet, but I'll likely have to revert this PR if we can't find a fix.

The only fix I can think of is to use JS to patch the transform position from react-beautiful-dnd, but that's hella brittle (see #123).

**Comment by JakeSidSmith** [comment]
> I only found out about it because of the bugs it caused. 😂

Ironically at least one of the bugs was related to drag and drop.

I shall have a look and see if I can find an easy fix.

**Comment by chrisvxd** [comment]
Sweet irony. Thanks @JakeSidSmith!

**Comment by JakeSidSmith** [comment]
Doesn't appear that an easy fix is available.

I think this is something that could/will resolve itself if the drag n drop library is changed (as in #123), and or the preview is rendered within an iframe.

Should probably roll this back until then.

**Comment by chrisvxd** [comment]
Thanks @JakeSidSmith. I'll revert this in an upcoming PR.

**Pull request merged**
