### PR TITLE
get Item error handling

### PR DESCRIPTION
**Pull request by prashanthvdckap**
get Item error handling if we get item props is undefined

### CODE REVIEW

**Review by chrisvxd — CHANGES_REQUESTED** [review]
Thanks @prashanthvdckap. Would you be able to provide steps to reproduce the underlying issue?

If it's hard to recreate, this is a pretty safe fix so I don't have an issue with it going in anyway.

However, please rebase your branch against `main` so that this can be merged.

**Comment by prashanthvdckap** [comment]
Hi @chrisvxd  I have replicated the error and please refer the video link

https://www.loom.com/share/a628903ffffc43ecb3be944b72757436?sid=1b76ba1d-daeb-4f72-b772-c125a512d8fb

**Comment by chrisvxd** [comment]
Hmm I can't see what's going on in the video. Can you share your config?

Furthermore, please run `yarn prettier` on your fix to address the formatting issues causing the tests to fail.

**Comment by prashanthvdckap** [comment]
Hi @chrisvxd  following is my config


`{
    "categories": {
        "Layout": {
            "components": [
                "Columns",
                "Flex",
                "Spacer"
            ]
        },
        "Typography": {
            "components": [
                "Text"
            ]
        },
        "Actions": {
            "components": [
                "Button"
            ]
        },
        "HTML": {
            "components": [
                "Html"
            ]
        },
        "Media": {
            "components": [
                "Image",
                "VideoPlayer"
            ]
        },
        "Product": {
            "components": [
                "ProductCard",
                "ProductSet"
            ]
        },
        "Carousel": {
            "components": [
                "Carousel"
            ]
        },
        "Others": {
            "components": [
                "Card",
                "HeroBanner"
            ]
        }
    },
    "components": {
        "Image": {
            "fields": {
                "ImageLink": {
                    "type": "custom"
                },
                "ImageAlt": {
                    "type": "custom"
                },
                "ImageHref": {
                    "type": "custom"
                },
                "ImageWidth": {
                    "type": "custom"
                },
                "ImageHeight": {
                    "type": "custom"
                },
                "ImageOpacity": {
                    "type": "custom"
                },
                "ImageAlign": {
                    "type": "custom"
                },
                "Margin": {
                    "type": "custom"
                },
                "Padding": {
                    "type": "custom"
                },
                "BorderStyle": {
                    "type": "custom"
                },
                "BorderColor": {
                    "type": "custom"
                },
                "BorderThickness": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "ImageLink": "",
                "ImageAlt": "",
                "ImageWidth": "200px",
                "ImageHeight": "200px",
                "ImageOpacity": "",
                "ImageAlign": "left",
                "Margin": {
                    "t": "",
                    "r": "",
                    "b": "",
                    "l": "",
                    "sameValue": false
                },
                "Padding": {
                    "t": "",
                    "r": "",
                    "b": "",
                    "l": "",
                    "sameValue": false
                },
                "BorderStyle": "none",
                "BorderColor": "000",
                "BorderThickness": ""
            }
        },
        
        "Columns": {
            "fields": {
                "distribution": {
                    "type": "custom"
                },
                "columns": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "distribution": "auto",
                "columns": [
                    {
                        "label": "Column",
                        "inputs": [
                            {
                                "label": "Span (1 - 12)",
                                "name": "span",
                                "value": ""
                            }
                        ],
                        "selected": true
                    },
                    {
                        "label": "Column",
                        "inputs": [
                            {
                                "label": "Span (1 - 12)",
                                "name": "span",
                                "value": ""
                            }
                        ],
                        "selected": false
                    }
                ]
            }
        },
        "Flex": {
            "fields": {
                "items": {
                    "type": "custom"
                },
                "minItemWidth": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "items": [
                    {
                        "label": "Item",
                        "inputs": [
                            {
                                "label": "Minimum Item Width",
                                "name": "minItemWidth",
                                "value": 0
                            }
                        ],
                        "selected": true
                    },
                    {
                        "label": "Item",
                        "inputs": [
                            {
                                "label": "Minimum Item Width",
                                "name": "minItemWidth",
                                "value": 0
                            }
                        ],
                        "selected": false
                    }
                ],
                "minItemWidth": 356
            }
        },
        "Text": {
            "fields": {
                "text": {
                    "type": "custom"
                },
                "size": {
                    "type": "custom"
                },
                "fontColor": {
                    "type": "custom"
                },
                "fontFamily": {
                    "type": "custom"
                },
                "fontWeight": {
                    "type": "custom"
                },
                "margin": {
                    "type": "custom"
                },
                "padding": {
                    "type": "custom"
                },
                "align": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "align": "left",
                "text": "Text",
                "fontWeight": 600,
                "size": "20",
                "color": "default",
                "fontColor": "000",
                "fontFamily": ""
            }
        },
        "Spacer": {
            "fields": {
                "size": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "size": "24"
            }
        },
        "VideoPlayer": {
            "fields": {
                "URL": {
                    "type": "custom"
                },
                "Auto Play": {
                    "type": "custom"
                },
                "Loop Video": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "URL": "",
                "Auto Play": true,
                "Loop Video": false
            }
        },
        "Carousel": {
            "fields": {
                "slides": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "slides": [
                    {
                        "carouselHeight": "600",
                        "redirectionLink": "https://www.google.com",
                        "containerAlignment": "left",
                        "containerHeading": "Carousel Title",
                        "containerDescription": "Add a description for your carousel slide. You can use this to promote multiple sales.",
                        "containerHeadingFontSize": "32",
                        "containerDescriptionFontSize": "16",
                        "backgroundType": "image",
                        "carouselBackgroundImage": "https://images.unsplash.com/photo-1517840600399-c7c2ff4c0fb5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
                        "containerButtonTextColor": "fff",
                        "containerButtonText": "Shop Now",
                        "containerButtonBackgroundColor": "c26431",
                        "carouselBackground": "fff",
                        "containerTextColor": "000",
                        "containerColor": "fff",
                        "selected": true,
                        "label": "Slide",
                        "name": "slide",
                        "id": 1
                    },
                    {
                        "carouselHeight": "600",
                        "redirectionLink": "https://www.google.com",
                        "containerAlignment": "left",
                        "containerHeading": "Carousel Title",
                        "containerDescription": "Add a description for your carousel slide. You can use this to promote multiple sales.",
                        "containerHeadingFontSize": "32",
                        "containerDescriptionFontSize": "16",
                        "backgroundType": "image",
                        "carouselBackgroundImage": "https://images.unsplash.com/photo-1517840600399-c7c2ff4c0fb5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
                        "containerButtonTextColor": "fff",
                        "containerButtonText": "Shop Now",
                        "containerButtonBackgroundColor": "c26431",
                        "carouselBackground": "fff",
                        "containerTextColor": "000",
                        "containerColor": "fff",
                        "selected": false,
                        "label": "Slide",
                        "name": "slide",
                        "id": 2
                    }
                ]
            }
        },
        "Html": {
            "fields": {
                "HTML": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "HTML": {
                    "data": "<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>",
                    "toggle": false
                }
            }
        },
        "Button": {
            "fields": {
                "ButtonLink": {
                    "type": "custom"
                },
                "ButtonText": {
                    "type": "custom"
                },
                "ButtonAlign": {
                    "type": "custom"
                },
                "ButtonMargin": {
                    "type": "custom"
                },
                "ButtonPadding": {
                    "type": "custom"
                },
                "FontFamily": {
                    "type": "custom"
                },
                "FontWeight": {
                    "type": "custom"
                },
                "FontSize": {
                    "type": "custom"
                },
                "TextColor": {
                    "type": "custom"
                },
                "TextHoverColor": {
                    "type": "custom"
                },
                "ButtonColor": {
                    "type": "custom"
                },
                "ButtonHoverColor": {
                    "type": "custom"
                },
                "BorderColor": {
                    "type": "custom"
                },
                "BorderHoverColor": {
                    "type": "custom"
                },
                "BorderThickness": {
                    "type": "custom"
                },
                "BorderRadius": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "ButtonLink": "#",
                "ButtonText": "Button",
                "ButtonAlign": "left",
                "ButtonMargin": {
                    "t": "",
                    "r": "",
                    "b": "",
                    "l": "",
                    "sameValue": false
                },
                "ButtonPadding": {
                    "t": "8",
                    "r": "24",
                    "b": "8",
                    "l": "24",
                    "sameValue": false
                },
                "FontFamily": "",
                "FontWeight": 400,
                "FontSize": "16",
                "TextColor": "fff",
                "TextHoverColor": "fff",
                "ButtonColor": "c26431",
                "ButtonHoverColor": "27303a",
                "BorderColor": "",
                "BorderHoverColor": "",
                "BorderThickness": "0",
                "BorderRadius": "0"
            }
        },
        "ProductCard": {
            "fields": {
                "product": {
                    "type": "custom"
                },
                "elements": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "product": "",
                "elements": [
                    {
                        "label": "Alignment",
                        "type": "direct",
                        "show": true,
                        "inputs": [
                            {
                                "label": "Alignment",
                                "name": "align",
                                "value": "center",
                                "type": "align"
                            }
                        ],
                        "selected": false
                    },
                    {
                        "label": "Product Name",
                        "type": "accordion",
                        "show": true,
                        "selected": false,
                        "inputs": [
                            {
                                "label": "Font Size",
                                "name": "fontSize",
                                "type": "range",
                                "min": 0,
                                "max": 100,
                                "value": 16
                            },
                            {
                                "label": "Font Weight",
                                "name": "fontWeight",
                                "type": "input",
                                "value": 400
                            },
                            {
                                "label": "Font Color",
                                "name": "color",
                                "type": "color",
                                "value": "000"
                            },
                            {
                                "label": "Font Family",
                                "name": "fontFamily",
                                "type": "dropdown",
                                "options": "fontFamily",
                                "value": ""
                            }
                        ]
                    },
                    {
                        "label": "Product Price",
                        "type": "accordion",
                        "show": true,
                        "selected": false,
                        "inputs": [
                            {
                                "label": "Font Size",
                                "name": "fontSize",
                                "type": "range",
                                "min": 0,
                                "max": 100,
                                "value": 16
                            },
                            {
                                "label": "Font Weight",
                                "name": "fontWeight",
                                "type": "input",
                                "value": 400
                            },
                            {
                                "label": "Font Color",
                                "name": "color",
                                "type": "color",
                                "value": "000"
                            },
                            {
                                "label": "Font Family",
                                "name": "fontFamily",
                                "type": "dropdown",
                                "options": "fontFamily",
                                "value": ""
                            }
                        ]
                    },
                    {
                        "label": "Product Button",
                        "type": "accordion",
                        "show": true,
                        "selected": false,
                        "inputs": [
                            {
                                "label": "Button Color",
                                "name": "buttonColor",
                                "type": "color",
                                "value": "000"
                            },
                            {
                                "label": "Button Text Color",
                                "name": "buttonTextColor",
                                "type": "color",
                                "value": "fff"
                            },
                            {
                                "label": "Button Action",
                                "type": "dropdown",
                                "name": "buttonAction",
                                "options": "buttonType",
                                "value": "Add to Cart"
                            }
                        ]
                    }
                ]
            }
        },
        "ProductSet": {
            "fields": {
                "products": {
                    "type": "custom"
                },
                "elements": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "products": [],
                "elements": [
                    {
                        "label": "Alignment",
                        "type": "direct",
                        "show": true,
                        "inputs": [
                            {
                                "label": "Alignment",
                                "name": "align",
                                "value": "center",
                                "type": "align"
                            }
                        ],
                        "selected": false
                    },
                    {
                        "label": "Product Name",
                        "type": "accordion",
                        "show": true,
                        "selected": false,
                        "inputs": [
                            {
                                "label": "Font Size",
                                "name": "fontSize",
                                "type": "range",
                                "min": 0,
                                "max": 100,
                                "value": 16
                            },
                            {
                                "label": "Font Weight",
                                "name": "fontWeight",
                                "type": "input",
                                "value": 400
                            },
                            {
                                "label": "Font Color",
                                "name": "color",
                                "type": "color",
                                "value": "000"
                            },
                            {
                                "label": "Font Family",
                                "name": "fontFamily",
                                "type": "dropdown",
                                "options": "fontFamily",
                                "value": ""
                            }
                        ]
                    },
                    {
                        "label": "Product Price",
                        "type": "accordion",
                        "show": true,
                        "selected": false,
                        "inputs": [
                            {
                                "label": "Font Size",
                                "name": "fontSize",
                                "type": "range",
                                "min": 0,
                                "max": 100,
                                "value": 16
                            },
                            {
                                "label": "Font Weight",
                                "name": "fontWeight",
                                "type": "input",
                                "value": 400
                            },
                            {
                                "label": "Font Color",
                                "name": "color",
                                "type": "color",
                                "value": "000"
                            },
                            {
                                "label": "Font Family",
                                "name": "fontFamily",
                                "type": "dropdown",
                                "options": "fontFamily",
                                "value": ""
                            }
                        ]
                    },
                    {
                        "label": "Product Button",
                        "type": "accordion",
                        "show": true,
                        "selected": false,
                        "inputs": [
                            {
                                "label": "Button Color",
                                "name": "buttonColor",
                                "type": "color",
                                "value": "000"
                            },
                            {
                                "label": "Button Text Color",
                                "name": "buttonTextColor",
                                "type": "color",
                                "value": "fff"
                            },
                            {
                                "label": "Button Action",
                                "type": "dropdown",
                                "name": "buttonAction",
                                "options": "buttonType",
                                "value": "Add to Cart"
                            }
                        ]
                    }
                ]
            }
        },
        "HeroBanner": {
            "fields": {
                "title": {
                    "type": "custom"
                },
                "description": {
                    "type": "custom"
                },
                "buttons": {
                    "type": "custom"
                },
                "align": {
                    "type": "custom"
                },
                "image": {
                    "type": "custom"
                },
                "imageMode": {
                    "type": "custom"
                },
                "padding": {
                    "type": "custom"
                }
            },
            "defaultProps": {
                "title": "Hero",
                "align": "left",
                "description": "Description",
                "imageMode": "inline",
                "buttons": [
                    {
                        "label": "Button",
                        "href": "#",
                        "variant": "primary",
                        "buttonBgColor": "c26431",
                        "buttonColor": "fff",
                        "selected": true,
                        "name": "button",
                        "id": 1
                    }
                ],
                "padding": 64
            }
        }
    },
    "root": {
        "fields": {}
    }
}`

**Review by chrisvxd — CHANGES_REQUESTED** [review]
Please run `yarn format` before I can merge this

**Comment by prashanthvdckap** [comment]
Done yarn formating

**Review by chrisvxd — APPROVED** [review]

**Comment by prashanthvdckap** [comment]
Hi @chrisvxd 
Thanks for approving,
when will this move to live version?

**Comment by chrisvxd** [comment]
@prashanthvdckap should be in `0.14.2-canary.4dbd487` shortly!

**Pull request merged**
