### PR TITLE
Adding a default favicon to the demo app

### LINKED ISSUE #259: Favicon getting caught by catch-all in next recipe
The favicon is getting caught by the catch-all route in the next recipe.

We should add a placeholder favicon, which will prevent the catch-all route from getting triggered.

### PR DESCRIPTION
**Pull request by xaviemirmon**
Closes #259

### CODE REVIEW

**Review by chrisvxd — CHANGES_REQUESTED** [review]
Thanks @xaviemirmon! The original issue actually relates to the favicon conflicting in the `next` _recipe_, rather than the demo app. I imagine this solution would fix that, too.

**Comment by xaviemirmon** [comment]
I got it, @chrisvxd. I'll also update the branch to account for this in the recipe.

**Comment by xaviemirmon** [comment]
@chrisvxd I've added this to the recipe also!

**Review by chrisvxd — APPROVED** [review]
🎉

**Pull request merged**
