### PR TITLE
array field undefined value length check

### PR DESCRIPTION
**Pull request by sagarchoudhary96**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
#179

**Comment by sagarchoudhary96** [comment]
@chrisvxd , sorry but there was one check which got missed in the previous fix. This should resolve the issue completely.

**Review by chrisvxd — APPROVED** [review]
Good catch, thanks again @sagarchoudhary96

**Comment by sagarchoudhary96** [comment]
@chrisvxd  what is the canary version for this change.

**Comment by chrisvxd** [comment]
`0.10.1-canary.68afd09`

They're automatically published on each merge with the commit, in this case `68afd09`. You should always be able to see it pop up a few minutes after merge on NPM: https://www.npmjs.com/package/@measured/puck?activeTab=versions

**Pull request merged**
